### ISSUE TITLE
Photo location field

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/RISKy#7]
This could link to #3 in that it would be useful to retain or store location info for photos from iNat, although this could just be done through a record ID field, given that this allows someone to discover location anyway.

More broadly than this though, can we have a location name field for species media photos? This could also be displayed with the name and licence.

**Comment by johnvanbreda** [comment]
@sacrevert are you proposing the following:
* On the species image edit tab (e.g. https://www.ris-ky.info/media/4/edit?destination=/admin/content/media) add fields for location name and licence.
* When viewing a species account in Cydas, add the location name and licence fields to each image on the carousel so they are visible along with the alternative text?

Note to self: you can only have 1 field for the image description on the Bootstrap Carousel view format, but can use rewriting to combine several field values together.

**Comment by sacrevert** [comment]
Yes, although I mean that they are visible as a title (where currently we just have the species name appearing in red), rather than just as a hover-over alternative text

**Comment by johnvanbreda** [comment]
Ok. I've done the following:
* Added location name field.
* Added an author field (since some of your labels have authors, it made sense to separate this out).
* Added a taxonomy called licences and populated it with a list of CC licences. You can add other licences here if needed.
* Added a licence field linked to the licences taxonomy.
* Modified the view which outputs the carousel to display the new info. The licence is shown as a code with a tooltip containing full info.

I've set up a demo of this on the 2nd image on Leucaena leucocephala. One remaining question for you @sacrevert:
* Do we need to cater for different versions of the licences? E.g. in the example image it was flagged as 4.0.

**Comment by sacrevert** [comment]
Wonderful. I suppose technically we should list the separate versions of the licences if you can get a list easily? Otherwise I can add them as and when. Many thanks!

**Comment by johnvanbreda** [comment]
2 options - add a separate licence version field to the image edit form, or you need to list all the different licence versions in the taxonomy. Up to you?

**Comment by sacrevert** [comment]
Probably easiest to add all the different versions to the taxonomy i think. The two bits of information are best kept together given that they directly indicate a specific licence text.

**Comment by johnvanbreda** [comment]
Ok - can I leave that to you then? You can just edit the terms in the taxonomy.

**Comment by sacrevert** [comment]
No worries.
